version: '3'

services:
  postgres:
    image: postgres:16
    container_name: test
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERname}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5555:5432'
    volumes:
      - ./src/database/postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-test
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - ./src/database/pgadmin:/var/lib/pgadmin